"""Emission compliance tests for sinks (auto-generated by pact).

NOTE: Emission protocol not yet implemented — these tests validate that
the module is importable.
"""

import pytest


class TestEmissionCompliance:
    """Verify sinks module is importable."""

    def test_disk_sink_importable(self):
        """DiskSink is importable from chronicler.sinks.disk."""
        from chronicler.sinks.disk import DiskSink
        assert DiskSink is not None

    def test_stigmergy_sink_importable(self):
        """StigmergySink is importable from chronicler.sinks.stigmergy."""
        from chronicler.sinks.stigmergy import StigmergySink
        assert StigmergySink is not None

    def test_apprentice_sink_importable(self):
        """ApprenticeSink is importable from chronicler.sinks.apprentice."""
        from chronicler.sinks.apprentice import ApprenticeSink
        assert ApprenticeSink is not None

    def test_kindex_sink_importable(self):
        """is_noteworthy is importable from chronicler.sinks.kindex."""
        from chronicler.sinks.kindex import is_noteworthy
        assert callable(is_noteworthy)
