"""Emission compliance tests for sources (auto-generated by pact).

NOTE: Emission protocol not yet implemented — these tests validate that
the module is importable.
"""

import pytest


class TestEmissionCompliance:
    """Verify sources module is importable."""

    def test_webhook_source_importable(self):
        """WebhookSource is importable from chronicler.sources.webhook."""
        from chronicler.sources.webhook import WebhookSource
        assert WebhookSource is not None

    def test_otlp_source_importable(self):
        """OtlpSource is importable from chronicler.sources.otlp."""
        from chronicler.sources.otlp import OtlpSource
        assert OtlpSource is not None

    def test_file_source_importable(self):
        """FileSource is importable from chronicler.sources.file."""
        from chronicler.sources.file import FileSource
        assert FileSource is not None

    def test_sentinel_source_importable(self):
        """SentinelSource is importable from chronicler.sources.sentinel."""
        from chronicler.sources.sentinel import SentinelSource
        assert SentinelSource is not None

    def test_emit_importable(self):
        """emit is importable from chronicler.sources.base."""
        from chronicler.sources.base import emit
        assert callable(emit)
